set nocompatible              " be iMproved, required

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
Plug 'mileszs/ack.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'tpope/vim-commentary'
Plug 'christoomey/vim-tmux-navigator'


call plug#end()

" Basic Settings "
set encoding=utf-8
syntax on
set number
set noshowmode
set hlsearch
set incsearch

let mapleader = " "

" Tabs and Spaces "
set expandtab " Make tabs indent with spaces
set tabstop=2 " Number of spaces for tab character
set shiftwidth=2 " Width when using > in normal mode
set softtabstop=2 " Set equal to tabspot

" Themes "
let g:airline_theme='simple'
colorscheme molokai

" Key Mappings "
:imap jj <ESC>
"
"
" Quickly insert an empty new line without entering insert mode
"


nmap <CR> O<esc>

map <C-n> :NERDTreeToggle<CR>
map <C-t> :FZF<CR>


let g:airline_powerline_fonts = 1
" Show buffers
let g:airline#extensions#tabline#enabled = 1
" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'

" Buffer remaps
set hidden " Allows to move between buffers while editing
nmap <leader>n :bnext<CR>

nmap <leader>p :bprevious<CR>
nmap <leader>bl :ls<CR>
" Close the current buffer and move to the previous one
nmap <leader>bd :bp <BAR> bd #<CR> 
nmap <leader>bD :bp <BAR> bd! #<CR> 

nmap <leader>q :q<CR>
nmap <leader>Q :q!<CR>

nmap <leader>v :nohlsearch<CR>

nmap <leader>f :Ack
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" yank to clipboard
if has("clipboard")
  set clipboard=unnamed " copy to the system clipboard
endif

" Show space, eol and tab characters
" set listchars=space:.,eol:¬,tab:>·
" set list
